package com.example.brandat.models.orderModel.discount

data class PriceRule(
    val admin_graphql_api_id: String = "",
    val allocation_limit: Any = Any(),
    val allocation_method: String = "",
    val created_at: String = "",
    val customer_segment_prerequisite_ids: List<Any> = listOf(),
    val customer_selection: String = "",
    val ends_at: Any = Any(),
    val entitled_collection_ids: List<Any> = listOf(),
    val entitled_country_ids: List<Any> = listOf(),
    val entitled_product_ids: List<Any> = listOf(),
    val entitled_variant_ids: List<Any> = listOf(),
    val id: Long = 0,
    val once_per_customer: Boolean = false,
    val prerequisite_collection_ids: List<Any> = listOf(),
    val prerequisite_customer_ids: List<Any> = listOf(),
    val prerequisite_product_ids: List<Any> = listOf(),
    val prerequisite_quantity_range: Any = Any(),
    val prerequisite_shipping_price_range: Any = Any(),
    val prerequisite_subtotal_range: Any = Any(),
    val prerequisite_to_entitlement_purchase: PrerequisiteToEntitlementPurchase = PrerequisiteToEntitlementPurchase(),
    val prerequisite_to_entitlement_quantity_ratio: PrerequisiteToEntitlementQuantityRatio = PrerequisiteToEntitlementQuantityRatio(),
    val prerequisite_variant_ids: List<Any> = listOf(),
    val starts_at: String = "",
    val target_selection: String = "",
    val target_type: String = "",
      val title: String = "",
    val updated_at: String = "",
    val usage_limit: Any = Any(),
    val value: String = "",
    val value_type: String = ""
)